# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adcvalues.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adcvalues.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x61\x64\x63values.proto\"R\n\nSerialData\x12\x0c\n\x04time\x18\x01 \x02(\x04\x12\x0c\n\x04\x61\x64\x63\x30\x18\x02 \x02(\r\x12\x0c\n\x04\x61\x64\x63\x31\x18\x03 \x02(\r\x12\x0c\n\x04\x61\x64\x63\x32\x18\x04 \x02(\r\x12\x0c\n\x04\x61\x64\x63\x33\x18\x05 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERIALDATA = _descriptor.Descriptor(
  name='SerialData',
  full_name='SerialData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='SerialData.time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc0', full_name='SerialData.adc0', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc1', full_name='SerialData.adc1', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc2', full_name='SerialData.adc2', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc3', full_name='SerialData.adc3', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['SerialData'] = _SERIALDATA

SerialData = _reflection.GeneratedProtocolMessageType('SerialData', (_message.Message,), dict(
  DESCRIPTOR = _SERIALDATA,
  __module__ = 'adcvalues_pb2'
  # @@protoc_insertion_point(class_scope:SerialData)
  ))
_sym_db.RegisterMessage(SerialData)


# @@protoc_insertion_point(module_scope)
