/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Sun Jun 12 10:57:36 2016. */

#include "adcvalues.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SerialData_fields[6] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, SerialData, time, time, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SerialData, adc0, time, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SerialData, adc1, adc0, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, SerialData, adc2, adc1, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, SerialData, adc3, adc2, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
