/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Sun Jun 12 10:57:36 2016. */

#ifndef PB_ADCVALUES_PB_H_INCLUDED
#define PB_ADCVALUES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SerialData {
    uint64_t time;
    uint32_t adc0;
    uint32_t adc1;
    uint32_t adc2;
    uint32_t adc3;
/* @@protoc_insertion_point(struct:SerialData) */
} SerialData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SerialData_init_default                  {0, 0, 0, 0, 0}
#define SerialData_init_zero                     {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SerialData_time_tag                      1
#define SerialData_adc0_tag                      2
#define SerialData_adc1_tag                      3
#define SerialData_adc2_tag                      4
#define SerialData_adc3_tag                      5

/* Struct field encoding specification for nanopb */
extern const pb_field_t SerialData_fields[6];

/* Maximum encoded size of messages (where known) */
#define SerialData_size                          35

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ADCVALUES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
